#!/bin/sh

# Compile with the C99 standard, warnings enabled, and with GDB support.
CFLAGS="-std=c99 -Wall -pedantic -Wextra -g"

# Compile all graphing algorithms
for gr in dijkstra.c kruskal.c; do
    "${CC:-cc}" $CFLAGS -o "${gr%%.c}" "$gr"
done
