#!/bin/sh

for f in *.c; do
    if ! clang-format --style=llvm "$f" | diff - "$f"; then
        echo "Formatting $f"
        clang-format --style=llvm -i "$f"
    fi
    "${CC:-cc}" -std=c99 -Wall -pedantic -o "${f%%.c}" "$f"
done
